/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AgentStatus = IDL.Variant({
  'Idle' : IDL.Null,
  'Active' : IDL.Null,
  'Offline' : IDL.Null,
});
export const Agent = IDL.Record({
  'id' : IDL.Text,
  'status' : AgentStatus,
  'lastActivity' : IDL.Int,
  'name' : IDL.Text,
  'roleDescription' : IDL.Text,
});
export const SystemStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ClientInfo = IDL.Record({
  'clientName' : IDL.Text,
  'systemStatus' : SystemStatus,
});
export const DailyBrief = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'recommendedActions' : IDL.Vec(IDL.Text),
  'topPriorities' : IDL.Vec(IDL.Text),
  'executiveSummary' : IDL.Text,
});
export const Layer = IDL.Record({
  'id' : IDL.Text,
  'completionPct' : IDL.Nat,
  'name' : IDL.Text,
  'statusLabel' : IDL.Text,
});
export const TrendDirection = IDL.Variant({
  'Up' : IDL.Null,
  'Down' : IDL.Null,
  'Flat' : IDL.Null,
});
export const Metric = IDL.Record({
  'taskAutomationPct' : IDL.Float64,
  'taskAutomationTarget' : IDL.Float64,
  'revenuePerEmployee' : IDL.Float64,
  'awayFromDeskTrend' : TrendDirection,
  'awayFromDeskTarget' : IDL.Float64,
  'revenuePerEmployeeTrend' : TrendDirection,
  'awayFromDeskHours' : IDL.Float64,
  'taskAutomationTrend' : TrendDirection,
  'revenuePerEmployeeTarget' : IDL.Float64,
});
export const UpdateAgentInput = IDL.Record({
  'status' : AgentStatus,
  'lastActivity' : IDL.Int,
});
export const UpdateClientInfoInput = IDL.Record({
  'clientName' : IDL.Text,
  'systemStatus' : SystemStatus,
});
export const UpdateDailyBriefInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'recommendedActions' : IDL.Vec(IDL.Text),
  'topPriorities' : IDL.Vec(IDL.Text),
  'executiveSummary' : IDL.Text,
});
export const UpdateLayerInput = IDL.Record({
  'completionPct' : IDL.Nat,
  'statusLabel' : IDL.Text,
});
export const UpdateMetricsInput = IDL.Record({
  'taskAutomationPct' : IDL.Float64,
  'taskAutomationTarget' : IDL.Float64,
  'revenuePerEmployee' : IDL.Float64,
  'awayFromDeskTrend' : TrendDirection,
  'awayFromDeskTarget' : IDL.Float64,
  'revenuePerEmployeeTrend' : TrendDirection,
  'awayFromDeskHours' : IDL.Float64,
  'taskAutomationTrend' : TrendDirection,
  'revenuePerEmployeeTarget' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
  'getClientInfo' : IDL.Func([], [ClientInfo], ['query']),
  'getDailyBrief' : IDL.Func([], [DailyBrief], ['query']),
  'getLayer' : IDL.Func([IDL.Text], [IDL.Opt(Layer)], ['query']),
  'getMetrics' : IDL.Func([], [Metric], ['query']),
  'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'listLayers' : IDL.Func([], [IDL.Vec(Layer)], ['query']),
  'updateAgent' : IDL.Func([IDL.Text, UpdateAgentInput], [IDL.Bool], []),
  'updateClientInfo' : IDL.Func([UpdateClientInfoInput], [], []),
  'updateDailyBrief' : IDL.Func([UpdateDailyBriefInput], [], []),
  'updateLayer' : IDL.Func([IDL.Text, UpdateLayerInput], [IDL.Bool], []),
  'updateMetrics' : IDL.Func([UpdateMetricsInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AgentStatus = IDL.Variant({
    'Idle' : IDL.Null,
    'Active' : IDL.Null,
    'Offline' : IDL.Null,
  });
  const Agent = IDL.Record({
    'id' : IDL.Text,
    'status' : AgentStatus,
    'lastActivity' : IDL.Int,
    'name' : IDL.Text,
    'roleDescription' : IDL.Text,
  });
  const SystemStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ClientInfo = IDL.Record({
    'clientName' : IDL.Text,
    'systemStatus' : SystemStatus,
  });
  const DailyBrief = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'recommendedActions' : IDL.Vec(IDL.Text),
    'topPriorities' : IDL.Vec(IDL.Text),
    'executiveSummary' : IDL.Text,
  });
  const Layer = IDL.Record({
    'id' : IDL.Text,
    'completionPct' : IDL.Nat,
    'name' : IDL.Text,
    'statusLabel' : IDL.Text,
  });
  const TrendDirection = IDL.Variant({
    'Up' : IDL.Null,
    'Down' : IDL.Null,
    'Flat' : IDL.Null,
  });
  const Metric = IDL.Record({
    'taskAutomationPct' : IDL.Float64,
    'taskAutomationTarget' : IDL.Float64,
    'revenuePerEmployee' : IDL.Float64,
    'awayFromDeskTrend' : TrendDirection,
    'awayFromDeskTarget' : IDL.Float64,
    'revenuePerEmployeeTrend' : TrendDirection,
    'awayFromDeskHours' : IDL.Float64,
    'taskAutomationTrend' : TrendDirection,
    'revenuePerEmployeeTarget' : IDL.Float64,
  });
  const UpdateAgentInput = IDL.Record({
    'status' : AgentStatus,
    'lastActivity' : IDL.Int,
  });
  const UpdateClientInfoInput = IDL.Record({
    'clientName' : IDL.Text,
    'systemStatus' : SystemStatus,
  });
  const UpdateDailyBriefInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'recommendedActions' : IDL.Vec(IDL.Text),
    'topPriorities' : IDL.Vec(IDL.Text),
    'executiveSummary' : IDL.Text,
  });
  const UpdateLayerInput = IDL.Record({
    'completionPct' : IDL.Nat,
    'statusLabel' : IDL.Text,
  });
  const UpdateMetricsInput = IDL.Record({
    'taskAutomationPct' : IDL.Float64,
    'taskAutomationTarget' : IDL.Float64,
    'revenuePerEmployee' : IDL.Float64,
    'awayFromDeskTrend' : TrendDirection,
    'awayFromDeskTarget' : IDL.Float64,
    'revenuePerEmployeeTrend' : TrendDirection,
    'awayFromDeskHours' : IDL.Float64,
    'taskAutomationTrend' : TrendDirection,
    'revenuePerEmployeeTarget' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(Agent)], ['query']),
    'getClientInfo' : IDL.Func([], [ClientInfo], ['query']),
    'getDailyBrief' : IDL.Func([], [DailyBrief], ['query']),
    'getLayer' : IDL.Func([IDL.Text], [IDL.Opt(Layer)], ['query']),
    'getMetrics' : IDL.Func([], [Metric], ['query']),
    'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'listLayers' : IDL.Func([], [IDL.Vec(Layer)], ['query']),
    'updateAgent' : IDL.Func([IDL.Text, UpdateAgentInput], [IDL.Bool], []),
    'updateClientInfo' : IDL.Func([UpdateClientInfoInput], [], []),
    'updateDailyBrief' : IDL.Func([UpdateDailyBriefInput], [], []),
    'updateLayer' : IDL.Func([IDL.Text, UpdateLayerInput], [IDL.Bool], []),
    'updateMetrics' : IDL.Func([UpdateMetricsInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };