/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : string,
  'status' : AgentStatus,
  'lastActivity' : bigint,
  'name' : string,
  'roleDescription' : string,
}
export type AgentStatus = { 'Idle' : null } |
  { 'Active' : null } |
  { 'Offline' : null };
export interface ClientInfo {
  'clientName' : string,
  'systemStatus' : SystemStatus,
}
export interface DailyBrief {
  'title' : string,
  'date' : string,
  'recommendedActions' : Array<string>,
  'topPriorities' : Array<string>,
  'executiveSummary' : string,
}
export interface Layer {
  'id' : string,
  'completionPct' : bigint,
  'name' : string,
  'statusLabel' : string,
}
export interface Metric {
  'taskAutomationPct' : number,
  'taskAutomationTarget' : number,
  'revenuePerEmployee' : number,
  'awayFromDeskTrend' : TrendDirection,
  'awayFromDeskTarget' : number,
  'revenuePerEmployeeTrend' : TrendDirection,
  'awayFromDeskHours' : number,
  'taskAutomationTrend' : TrendDirection,
  'revenuePerEmployeeTarget' : number,
}
export type SystemStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Pending' : null };
export type TrendDirection = { 'Up' : null } |
  { 'Down' : null } |
  { 'Flat' : null };
export interface UpdateAgentInput {
  'status' : AgentStatus,
  'lastActivity' : bigint,
}
export interface UpdateClientInfoInput {
  'clientName' : string,
  'systemStatus' : SystemStatus,
}
export interface UpdateDailyBriefInput {
  'title' : string,
  'date' : string,
  'recommendedActions' : Array<string>,
  'topPriorities' : Array<string>,
  'executiveSummary' : string,
}
export interface UpdateLayerInput {
  'completionPct' : bigint,
  'statusLabel' : string,
}
export interface UpdateMetricsInput {
  'taskAutomationPct' : number,
  'taskAutomationTarget' : number,
  'revenuePerEmployee' : number,
  'awayFromDeskTrend' : TrendDirection,
  'awayFromDeskTarget' : number,
  'revenuePerEmployeeTrend' : TrendDirection,
  'awayFromDeskHours' : number,
  'taskAutomationTrend' : TrendDirection,
  'revenuePerEmployeeTarget' : number,
}
export interface _SERVICE {
  'getAgent' : ActorMethod<[string], [] | [Agent]>,
  'getClientInfo' : ActorMethod<[], ClientInfo>,
  'getDailyBrief' : ActorMethod<[], DailyBrief>,
  'getLayer' : ActorMethod<[string], [] | [Layer]>,
  'getMetrics' : ActorMethod<[], Metric>,
  'listAgents' : ActorMethod<[], Array<Agent>>,
  'listLayers' : ActorMethod<[], Array<Layer>>,
  'updateAgent' : ActorMethod<[string, UpdateAgentInput], boolean>,
  'updateClientInfo' : ActorMethod<[UpdateClientInfoInput], undefined>,
  'updateDailyBrief' : ActorMethod<[UpdateDailyBriefInput], undefined>,
  'updateLayer' : ActorMethod<[string, UpdateLayerInput], boolean>,
  'updateMetrics' : ActorMethod<[UpdateMetricsInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];