/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateDailyBriefInput {
    title: string;
    date: string;
    recommendedActions: Array<string>;
    topPriorities: Array<string>;
    executiveSummary: string;
}
export interface UpdateLayerInput {
    completionPct: bigint;
    statusLabel: string;
}
export interface UpdateClientInfoInput {
    clientName: string;
    systemStatus: SystemStatus;
}
export interface UpdateMetricsInput {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: TrendDirection;
    revenuePerEmployeeTarget: number;
}
export interface Metric {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: TrendDirection;
    revenuePerEmployeeTarget: number;
}
export interface DailyBrief {
    title: string;
    date: string;
    recommendedActions: Array<string>;
    topPriorities: Array<string>;
    executiveSummary: string;
}
export interface Agent {
    id: string;
    status: AgentStatus;
    lastActivity: bigint;
    name: string;
    roleDescription: string;
}
export interface UpdateAgentInput {
    status: AgentStatus;
    lastActivity: bigint;
}
export interface ClientInfo {
    clientName: string;
    systemStatus: SystemStatus;
}
export interface Layer {
    id: string;
    completionPct: bigint;
    name: string;
    statusLabel: string;
}
export enum AgentStatus {
    Idle = "Idle",
    Active = "Active",
    Offline = "Offline"
}
export enum SystemStatus {
    Inactive = "Inactive",
    Active = "Active",
    Pending = "Pending"
}
export enum TrendDirection {
    Up = "Up",
    Down = "Down",
    Flat = "Flat"
}
export interface backendInterface {
    getAgent(id: string): Promise<Agent | null>;
    getClientInfo(): Promise<ClientInfo>;
    getDailyBrief(): Promise<DailyBrief>;
    getLayer(id: string): Promise<Layer | null>;
    getMetrics(): Promise<Metric>;
    listAgents(): Promise<Array<Agent>>;
    listLayers(): Promise<Array<Layer>>;
    updateAgent(id: string, input: UpdateAgentInput): Promise<boolean>;
    updateClientInfo(input: UpdateClientInfoInput): Promise<void>;
    updateDailyBrief(input: UpdateDailyBriefInput): Promise<void>;
    updateLayer(id: string, input: UpdateLayerInput): Promise<boolean>;
    updateMetrics(input: UpdateMetricsInput): Promise<void>;
}
import type { Agent as _Agent, AgentStatus as _AgentStatus, ClientInfo as _ClientInfo, Layer as _Layer, Metric as _Metric, SystemStatus as _SystemStatus, TrendDirection as _TrendDirection, UpdateAgentInput as _UpdateAgentInput, UpdateClientInfoInput as _UpdateClientInfoInput, UpdateMetricsInput as _UpdateMetricsInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAgent(arg0: string): Promise<Agent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientInfo(): Promise<ClientInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientInfo();
                return from_candid_ClientInfo_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientInfo();
            return from_candid_ClientInfo_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyBrief(): Promise<DailyBrief> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyBrief();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyBrief();
            return result;
        }
    }
    async getLayer(arg0: string): Promise<Layer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLayer(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLayer(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<Metric> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return from_candid_Metric_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return from_candid_Metric_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgents();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgents();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLayers(): Promise<Array<Layer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLayers();
            return result;
        }
    }
    async updateAgent(arg0: string, arg1: UpdateAgentInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, to_candid_UpdateAgentInput_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, to_candid_UpdateAgentInput_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClientInfo(arg0: UpdateClientInfoInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientInfo(to_candid_UpdateClientInfoInput_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientInfo(to_candid_UpdateClientInfoInput_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDailyBrief(arg0: UpdateDailyBriefInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyBrief(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyBrief(arg0);
            return result;
        }
    }
    async updateLayer(arg0: string, arg1: UpdateLayerInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLayer(arg0, arg1);
            return result;
        }
    }
    async updateMetrics(arg0: UpdateMetricsInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMetrics(to_candid_UpdateMetricsInput_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMetrics(to_candid_UpdateMetricsInput_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AgentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Agent_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ClientInfo_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientInfo): ClientInfo {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Metric_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Metric): Metric {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatus): SystemStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TrendDirection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrendDirection): TrendDirection {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Agent]): Agent | null {
    return value.length === 0 ? null : from_candid_Agent_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Layer]): Layer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: _TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: _TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: _TrendDirection;
    revenuePerEmployeeTarget: number;
}): {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: TrendDirection;
    revenuePerEmployeeTarget: number;
} {
    return {
        taskAutomationPct: value.taskAutomationPct,
        taskAutomationTarget: value.taskAutomationTarget,
        revenuePerEmployee: value.revenuePerEmployee,
        awayFromDeskTrend: from_candid_TrendDirection_n13(_uploadFile, _downloadFile, value.awayFromDeskTrend),
        awayFromDeskTarget: value.awayFromDeskTarget,
        revenuePerEmployeeTrend: from_candid_TrendDirection_n13(_uploadFile, _downloadFile, value.revenuePerEmployeeTrend),
        awayFromDeskHours: value.awayFromDeskHours,
        taskAutomationTrend: from_candid_TrendDirection_n13(_uploadFile, _downloadFile, value.taskAutomationTrend),
        revenuePerEmployeeTarget: value.revenuePerEmployeeTarget
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AgentStatus;
    lastActivity: bigint;
    name: string;
    roleDescription: string;
}): {
    id: string;
    status: AgentStatus;
    lastActivity: bigint;
    name: string;
    roleDescription: string;
} {
    return {
        id: value.id,
        status: from_candid_AgentStatus_n4(_uploadFile, _downloadFile, value.status),
        lastActivity: value.lastActivity,
        name: value.name,
        roleDescription: value.roleDescription
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientName: string;
    systemStatus: _SystemStatus;
}): {
    clientName: string;
    systemStatus: SystemStatus;
} {
    return {
        clientName: value.clientName,
        systemStatus: from_candid_SystemStatus_n8(_uploadFile, _downloadFile, value.systemStatus)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Up: null;
} | {
    Down: null;
} | {
    Flat: null;
}): TrendDirection {
    return "Up" in value ? TrendDirection.Up : "Down" in value ? TrendDirection.Down : "Flat" in value ? TrendDirection.Flat : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Idle: null;
} | {
    Active: null;
} | {
    Offline: null;
}): AgentStatus {
    return "Idle" in value ? AgentStatus.Idle : "Active" in value ? AgentStatus.Active : "Offline" in value ? AgentStatus.Offline : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Pending: null;
}): SystemStatus {
    return "Inactive" in value ? SystemStatus.Inactive : "Active" in value ? SystemStatus.Active : "Pending" in value ? SystemStatus.Pending : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AgentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): _AgentStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_SystemStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemStatus): _SystemStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TrendDirection_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrendDirection): _TrendDirection {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateAgentInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateAgentInput): _UpdateAgentInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateClientInfoInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateClientInfoInput): _UpdateClientInfoInput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMetricsInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMetricsInput): _UpdateMetricsInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AgentStatus;
    lastActivity: bigint;
}): {
    status: _AgentStatus;
    lastActivity: bigint;
} {
    return {
        status: to_candid_AgentStatus_n18(_uploadFile, _downloadFile, value.status),
        lastActivity: value.lastActivity
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientName: string;
    systemStatus: SystemStatus;
}): {
    clientName: string;
    systemStatus: _SystemStatus;
} {
    return {
        clientName: value.clientName,
        systemStatus: to_candid_SystemStatus_n22(_uploadFile, _downloadFile, value.systemStatus)
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: TrendDirection;
    revenuePerEmployeeTarget: number;
}): {
    taskAutomationPct: number;
    taskAutomationTarget: number;
    revenuePerEmployee: number;
    awayFromDeskTrend: _TrendDirection;
    awayFromDeskTarget: number;
    revenuePerEmployeeTrend: _TrendDirection;
    awayFromDeskHours: number;
    taskAutomationTrend: _TrendDirection;
    revenuePerEmployeeTarget: number;
} {
    return {
        taskAutomationPct: value.taskAutomationPct,
        taskAutomationTarget: value.taskAutomationTarget,
        revenuePerEmployee: value.revenuePerEmployee,
        awayFromDeskTrend: to_candid_TrendDirection_n26(_uploadFile, _downloadFile, value.awayFromDeskTrend),
        awayFromDeskTarget: value.awayFromDeskTarget,
        revenuePerEmployeeTrend: to_candid_TrendDirection_n26(_uploadFile, _downloadFile, value.revenuePerEmployeeTrend),
        awayFromDeskHours: value.awayFromDeskHours,
        taskAutomationTrend: to_candid_TrendDirection_n26(_uploadFile, _downloadFile, value.taskAutomationTrend),
        revenuePerEmployeeTarget: value.revenuePerEmployeeTarget
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): {
    Idle: null;
} | {
    Active: null;
} | {
    Offline: null;
} {
    return value == AgentStatus.Idle ? {
        Idle: null
    } : value == AgentStatus.Active ? {
        Active: null
    } : value == AgentStatus.Offline ? {
        Offline: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    Pending: null;
} {
    return value == SystemStatus.Inactive ? {
        Inactive: null
    } : value == SystemStatus.Active ? {
        Active: null
    } : value == SystemStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrendDirection): {
    Up: null;
} | {
    Down: null;
} | {
    Flat: null;
} {
    return value == TrendDirection.Up ? {
        Up: null
    } : value == TrendDirection.Down ? {
        Down: null
    } : value == TrendDirection.Flat ? {
        Flat: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
